@startuml

[*] --> Root
Dictionary : Keeps track of nesting
Root --> Dictionary : "<<"
Dictionary --> Dictionary : "<<" or ">>"
Dictionary --> Root : ">>"
Dictionary --> Key : "/"
Key --> KeyValueSeparator : " "
Key --> Value : "/" or "\\n"
KeyValueSeparator --> Value : "/" or Non Whitespace
Value --> Key : "/"
Value --> Dictionary : "\\n"
Dictionary --> Comment : "%"
Comment --> Dictionary : "\\n"
Key --> ValueInParenthesis : "("
KeyValueSeparator --> ValueInParenthesis : "("
Value --> ValueInParenthesis : "("
ValueInParenthesis --> Value : ")"
Key --> ValueInBrackets : "["
KeyValueSeparator --> ValueInBrackets : "["
Value --> ValueInBrackets : "["
ValueInBrackets --> Value : "]"
Root --> [*]

@enduml