@startuml

component Header as PDFHeader {
    component versionNumber {
    }
}

component Body {
    component "............"
}

component CrossReferenceTable {
    component CrossReferenceSection {
        component byteOffset {
        }

        component generationNumber {
        }

        component inUseOrFreeKeyword {
        }

        component EOL {
        }

        byteOffset - generationNumber
        generationNumber - inUseOrFreeKeyword
        inUseOrFreeKeyword - EOL
    }
}

component Trailer {
    component TrailerMarker {
    }

    component TrailerDictionary {
    }

    component StartXRefMarker {
    }

    component ByteOffsetLastCrossReferenceSection {
    }

    component EOFMarker {
    }

    TrailerMarker - TrailerDictionary
    TrailerDictionary - StartXRefMarker
    StartXRefMarker - ByteOffsetLastCrossReferenceSection
    ByteOffsetLastCrossReferenceSection - EOFMarker
}

PDFHeader -down- Body
Body -down- CrossReferenceTable
CrossReferenceTable -down- Trailer

@enduml